export const HTTP_MESSEGES = {
    USER_EXIST : "USER ALREADY EXISTS",
    USER_NOT_FOUND : "USER NOT FOUND",
    FORRIBDEN : "YOU ARE NOT ALLOWED",
    INVALID_CREDENTIAL : "INVALID EMAIL OR PASSWORD",
    UNAUTHOROZIED : 'ACCESS DENIED',
    LOGIN : "LOGIN SUCCESSFULL",
    REGISTER : "REGISTRATION COMPLETED"
}
